# This file was generated by GoReleaser. DO NOT EDIT.
cask "waba-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "837f9c2fd26c97750a4ddc724a6a9f08d705b1a3d115f11f9e79ad35d6614aa2"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "95b659315cd2f93ee13d13a2fc1e287175f66a4be9665eae0613ed334c8462e4"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d4c278937d1f71aa5c071a0870b49b2c16d738b95df7fea6b4cacfebf6f0d9d"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8a7a13178eadb1b6bdcf906319cc9e5fb6053dce25bf73aa6cadf0e265899b0d"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "waba-cli"
  desc "WhatsApp Cloud API from the command line"
  homepage "https://github.com/jjuanrivvera/waba-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waba"

  postflight do
    # An unsigned binary is SIGKILLed by Gatekeeper on macOS arm64 unless the
    # quarantine attribute is stripped.
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waba"]
  end

  # No zap stanza required

end
