# This file was generated by GoReleaser. DO NOT EDIT.
cask "waba-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "477041600748c18321646e225ae81cb45a6b0158b34a874dd5529ce7e26860ee"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb2c25ab4b358d6d81ad7c8b957dbbee7263b6b6fc31e5e52a4334490b26a5a5"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d117e6d3532655b0745ba1873315196db88417b43814478ea4cce0f1c1c954d"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "78ce7a367c8e4ce459f8cfec6306156a6d73fbd5a7b9999cc3924195faa5ad90"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "waba-cli"
  desc "WhatsApp Cloud API from the command line"
  homepage "https://github.com/jjuanrivvera/waba-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waba"

  postflight do
    # An unsigned binary is SIGKILLed by Gatekeeper on macOS arm64 unless the
    # quarantine attribute is stripped.
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waba"]
  end

  # No zap stanza required

end
