# This file was generated by GoReleaser. DO NOT EDIT.
cask "waba-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "103ad5b36a7da6ea6f4bd15c7cfe45b40e01be1bdb54727140b9ec95a7c2becb"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1079969b6b763509b00950fa578fcbd811974cf0d58964608c5638f932c0d2f2"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42a8c13eb590edd62ab6376fe53d61eaface9ca62e7e97035c49a4b10df7974f"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "78fe2fea37684e87a966cdf9ac83c4c1611ae4b90f8fc9a0e670bf461df23011"
      url "https://github.com/jjuanrivvera/waba-cli/releases/download/v#{version}/waba-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "waba-cli"
  desc "WhatsApp Cloud API from the command line"
  homepage "https://github.com/jjuanrivvera/waba-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waba"

  postflight do
    # An unsigned binary is SIGKILLed by Gatekeeper on macOS arm64 unless the
    # quarantine attribute is stripped.
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/waba"]
  end

  # No zap stanza required

end
